### PR TITLE
Next web

### PR DESCRIPTION
**Pull request by damiecode**

### CODE REVIEW

**Review by uche-inyama — CHANGES_REQUESTED** [review]
## Hi! you have done a great job :smiley: 

However, there are changes that need to be made

- [x] Validate your Html
 
### These instruction below shows how to make different sections of your webpage responsive.

### Navigation bar

   #### Large version


   - [x] It contains main navigation row.

- [x]  It contains sub-navigation row.

 - [x] It contains search icon at the rightmost side of sub-navigation row.


#### Medium version changes


 - [x] TWN logo appears at the leftmost part.


#### Small version changes


 - [x] Navigation and sub-navigation row changes to a hamburger (bars) icon at the rightmost part (next to seach icon).


### Top 3 articles section


 - [x] It contains 3 articles with an image as a background.


### Large version


- [x] It contains one bigger image on the leftmost part of the row (around two thirds of the width).

 - [x] It contains two smaller images on the rightmost part of the row (one above another).

 - [x] It contains TWN logo at the top left corner of the row.


### Medium version changes


 - [x] TWN logo disappears.


#### Small version changes


 - [x] All images take the maximum width and are are aligned in one column.


#### Latest news section

#### Large version


 - [x] It contains a header with the section name.

 - [x] It aligns 4 articles per row.

 - [x] Each article has a cover image and title placed below the image.


#### Medium version changes


- [x]  It aligns 3 articles per row.


#### Small version changes


 - [x] It aligns 1 articles per row.

 - [x] Each articles has a cover image on the left side and title on the right side of the row.


#### Latest Funding section

#### Large version


 - [x] It contains a header with the section name.

 - [ ] It aligns 4 articles per row.


#### Medium version changes


 - [ ] It aligns 3 articles per row.


#### Small version changes


 - [ ] It aligns 1 articles per row.


#### Categories (Apps, GERA, Tech, etc) section

#### Large version


 - [ ] It contains a header with the section name.

 - [ ] It aligns 3 category boxes per row.


#### Medium version changes


 - [ ] It aligns 2 category boxes per row.


#### Small version changes


 - [ ] It aligns 1 category box per row.


#### Latest deals section

#### Large version


 - [ ] It contains a header with the section name.

 It aligns 4 deals per row.


#### Medium version changes


 - [ ] It aligns 3 deals per row.


#### Small version changes


 - [ ] It aligns 1 deal per row.


#### Footer


 - [ ] It does not change through breakpoints.


 - [ ] It contains social media icons vertically and horizontally aligned.

 - [ ] It contains TNW logo with a copyright paragraph.


#### Implementation details


 - [ ] CSS styles should use media queries for 3 breakpoints
### Edit your media query to apply these changes.


``` small: max-width around 700; medium: max-width around 1000; large: mwidth over 1000 ```


### Implement these changes and submit another form for a code review :muscle:

**Comment by damiecode** [comment]
Please can you explain more, we really don't understand what we should do with the list.Thanks

**Comment by Torres-ssf** [comment]
### Pull Request Under Review By Sérgio (TSE)

**Review by Torres-ssf — APPROVED** [review]
### Great job implementing these changes team 👏 

I'm **approving** this project 👍 🎉 . Go on and merge to master.

Good luck on the next project and happy coding 💻 

**[FOR FUTURE PROJECTS]**

- Nice job not naming the branch of dev/developer. But next time try to give a feature name for the branch(e.g. 'created_sidebar' or 'added_comments_section'), just like it said in the Github flow [instructions](https://microverse.pathwright.com/library/microverse-onboarding/86777/path/step/53987922/). 

- Try to use meaningful names for the Pull Requests, it will make you repo looks even more professional.

**Comment by damiecode** [comment]
Thanks.

**Review by uche-inyama — COMMENTED** [review]
### Hi Dami! :smiley: 
I can see that your project have been approved :+1: 
I also saw your comment about the list, if you still need clarification you can reach me on slack with Inyama, Uchechukwu Henry

**Pull request merged**
